
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
public class StudentsGuiDesignCrud extends javax.swing.JFrame {

    public StudentsGuiDesignCrud() {
        setTitle("Students Entry Form");
        initComponents();
        DisplayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rolltxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        leveltxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        divisiontxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        majortxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        insertbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        displaybtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDisplay = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(148, 244, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Students Entry Form");
        jPanel1.add(jLabel1);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Roll No");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 16, 63, -1));
        jPanel2.add(rolltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 13, 350, -1));
        jPanel2.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 48, 350, -1));

        jLabel3.setText("Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 51, 63, -1));

        jLabel4.setText("Level");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 86, 63, -1));
        jPanel2.add(leveltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 83, 350, -1));

        jLabel5.setText("Division");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 121, 63, -1));
        jPanel2.add(divisiontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 118, 350, -1));

        jLabel6.setText("Major");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 156, 63, -1));

        majortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majortxtActionPerformed(evt);
            }
        });
        jPanel2.add(majortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 153, 350, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        insertbtn.setBackground(new java.awt.Color(57, 186, 109));
        insertbtn.setText("Insert");
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });
        jPanel3.add(insertbtn);

        updatebtn.setBackground(new java.awt.Color(57, 186, 109));
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel3.add(updatebtn);

        deletebtn.setBackground(new java.awt.Color(255, 153, 153));
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel3.add(deletebtn);

        displaybtn.setBackground(new java.awt.Color(57, 186, 109));
        displaybtn.setText("Display");
        displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybtnActionPerformed(evt);
            }
        });
        jPanel3.add(displaybtn);

        tableDisplay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Roll No", "Name", "Level", "Division", "Major"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableDisplay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tableDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void majortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_majortxtActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        String rolldelete = JOptionPane.showInputDialog("Enter Roll number for delete:");
        try {
            String URL = "jdbc:mysql://localhost:3306/college";
            String username = "root";
            String password = "";
            Connection conn = DriverManager.getConnection(URL, username, password);

            String deleteQuery = "DELETE FROM student WHERE id= (?)";
            PreparedStatement pstmt = conn.prepareStatement(deleteQuery);

            pstmt.setInt(1, Integer.parseInt(rolldelete));
            Component frame = null;
            int rowAffected = pstmt.executeUpdate();
            if (rowAffected > 0) {
                JOptionPane.showMessageDialog(frame, "Record Delete Successfully ");
            } else {
                JOptionPane.showMessageDialog(frame, "Error while Deleting record... ");
            }
            DisplayTable();
        } catch (NumberFormatException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_deletebtnActionPerformed


    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        try {
            String URL = "jdbc:mysql://localhost:3306/college";
            String username = "root";
            String password = "";
            Connection conn = DriverManager.getConnection(URL, username, password);

            String updateQuery = "UPDATE student SET name = ?, level = ?, division = ?, major = ? WHERE id = ?";
            PreparedStatement pstmt = conn.prepareStatement(updateQuery);

            // Insert first record
            pstmt.setInt(5, Integer.parseInt(rolltxt.getText()));
            pstmt.setString(1, nametxt.getText());
            pstmt.setString(2, leveltxt.getText());
            pstmt.setString(3, divisiontxt.getText());
            pstmt.setString(4, majortxt.getText());
            int rowAffected = pstmt.executeUpdate();
            Component frame = null;
            if (rowAffected > 0) {
                JOptionPane.showMessageDialog(frame, "Record Update Successfully ");
            } else {
                JOptionPane.showMessageDialog(frame, "Error while Update record... ");
            }
            DisplayTable();
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
        // TODO add your handling code here:
        try {
            String URL = "jdbc:mysql://localhost:3306/college";
            String username = "root";
            String password = "";
            Connection conn = DriverManager.getConnection(URL, username, password);

            String insertQuery = "INSERT INTO student VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(insertQuery);

            // Insert first record
            pstmt.setInt(1, Integer.parseInt(rolltxt.getText()));
            pstmt.setString(2, nametxt.getText());
            pstmt.setString(3, leveltxt.getText());
            pstmt.setString(4, divisiontxt.getText());
            pstmt.setString(5, majortxt.getText());
            int rowAffected = pstmt.executeUpdate();
            Component frame = null;
            if (rowAffected > 0) {
                JOptionPane.showMessageDialog(frame, "Record Insert Successfully ");
            } else {
                JOptionPane.showMessageDialog(frame, "Error while inserting record... ");
            }
            DisplayTable();
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_insertbtnActionPerformed

    public void InsertFunction() {
    }

    private void displaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybtnActionPerformed
        DisplayTable();
    }//GEN-LAST:event_displaybtnActionPerformed
    //    function to display data in tables and thsi functio is called in display button , after inser , update,delete
    public void DisplayTable() {
        try {
            String URL = "jdbc:mysql://localhost:3306/college";
            String username = "root";
            String password = "";
            Connection conn = DriverManager.getConnection(URL, username, password);

            String displayQuery = "SELECT * FROM student";
            PreparedStatement pstmt = conn.prepareStatement(displayQuery);

            ResultSet rs = pstmt.executeQuery();
            DefaultTableModel tblModel = (DefaultTableModel) tableDisplay.getModel();
            tblModel.setRowCount(0); // Clear the existing rows

            while (rs.next()) {
                int roll = rs.getInt(1);
                String name = rs.getString(2);
                String level = rs.getString(3);
                String div = rs.getString(4);
                String major = rs.getString(5);

                Object[] tblData = {roll, name, level, div, major};
                tblModel.addRow(tblData);
            }

            rs.close();
            pstmt.close();
            conn.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsGuiDesignCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsGuiDesignCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsGuiDesignCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsGuiDesignCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsGuiDesignCrud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton displaybtn;
    private javax.swing.JTextField divisiontxt;
    private javax.swing.JButton insertbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField leveltxt;
    private javax.swing.JTextField majortxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField rolltxt;
    private javax.swing.JTable tableDisplay;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
